---
- name: update loris logging config
  ini_file:
    path: /etc/loris2/loris2.conf
    owner: loris
    group: loris
    section: logging
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: "log_level"
      value: "'{{ loris_log_level }}'"
    - option: "max_size"
      value: "{{ loris_log_max_size }}"
    - option: "max_backups"
      value: "{{ loris_log_max_backups }}"
  notify: restart apache
  tags: loris_config
