---
- name: run the equivalent of apt-get update
  apt:
    update_cache: yes
  tags: apt

- name: install python3 dependencies
  apt:
    name:
      - python3-pip
      - python3-dev
      - python3-setuptools
  tags: apt

- name: install required image libraries
  apt:
    state: latest # override default
    update-cache: yes
    name:
      - libjpeg-turbo8-dev
      - libfreetype6-dev
      - zlib1g-dev
      - liblcms2-dev
      - liblcms2-utils
      - libtiff5-dev
      - libwebp-dev
  tags: apt

- name: create loris group
  group:
    name: loris
    state: present
  tags: users

- name: create loris user
  user:
    name: loris
    groups: loris
    create_home: yes
    state: present
  tags: users